"""
p
Inherits: BaseStrategy (Kelly sizing, ATR stops, DCA, max-DD cap, loss-streak pause)
Strategy type (inferred from class name): regime
Indicators (inferred): atr, ema, rsi, adx
Concept keywords: e, e, wavelet, momentum

This file is auto-generated by the BTQuant agency. It is a FULL strategy —
not a demo stub. Every bar calls BaseStrategy.next() which:
  1. Updates trailing stop
  2. Enforces max-hold-time exit
  3. Gates new entries on drawdown + daily-loss + loss-streak
  4. Sizes the position (Kelly / vol-target / fixed)
  5. Optionally scale-ins via DCA on adverse moves
  6. Places ATR-based stop + take-profit orders
  7. Ratchets the stop on favourable moves
"""
import backtrader as bt
import backtrader.indicators as btind

from backtrader.strategies.base import BaseStrategy


class E2E_Wavelet_Momentum(BaseStrategy):
    """p"""

    params = (
        # The base's percent_sizer defaults to 0, and an order of size 0 is
        # never filled. Set it or the strategy loads and never trades.
        ("percent_sizer", 0.95),
        # Inherit all BaseStrategy params, then add strategy-specific overrides
        ("verbose_log", False),
    )

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        super().__init__()
        self.ema = btind.EMA(self.data.close, period=self.p.ema_period)
        self.ema_fast = btind.EMA(self.data.close, period=self.p.ema_fast_period)
        self.ema_slow = btind.EMA(self.data.close, period=self.p.ema_slow_period)
        self.rsi = btind.RSI(self.data.close, period=self.p.rsi_period)
        self.adx = btind.ADX(self.data, period=14)

    def _entry_signal(self) -> bool:
            # Regime filter: only trade when ADX confirms trend strength
            trending = self.adx[0] > 20
            ema_bull = self.ema_fast[0] > self.ema_slow[0]
            rsi_pullback = 40 < self.rsi[0] < 60
            return trending and ema_bull and rsi_pullback

    def _exit_signal(self) -> bool:
            regime_lost = self.adx[0] < 15
            ema_bear = self.ema_fast[0] < self.ema_slow[0]
            return regime_lost or ema_bear
