"""
E2E_Momentum_RSI
Schema: v9_concept_driven (autonomous_agency safety net)
Source hypothesis: p
Strategy type (inferred): mean_reversion
Indicators (inferred): ema, rsi, atr
Concept keywords: e, e, momentum, rsi
Logic keywords (contribute code): (none)
Logic notes: (none)
Dropped as redundant (already implied by the base signal): (none)

Auto-generated by StrategyFactory._generate_concept_driven_code —
decomposes the hypothesis name into concept-driven logic blocks
(kalman, hawkes, wavelet, wasserstein, golden, etc.) and composes
a real BaseStrategy-pattern file. Header describes what the code does.
"""

from backtrader.strategies.base import BaseStrategy, bt


class E2E_Momentum_RSI(BaseStrategy):
    """E2E_Momentum_RSI (mean_reversion variant, concepts: (none))"""

    params = (
        ("ema_period", 21),
        ("ema_fast_period", 12),
        ("ema_slow_period", 26),
        ("rsi_period", 14),
        # BaseStrategy sizes every order from percent_sizer. Its own default
        # is 0, and an order of size 0 is never filled — without this line
        # the strategy loads, runs and trades nothing.
        ('percent_sizer', 0.95),
        ('stop_loss', 2.0),
        ('stop_trail', 1.5),
        ('take_profit', 4.0),
        ('debug', False),
    )

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.ema = bt.ind.EMA(self.data.close, period=self.p.ema_period)
        self.ema_fast = bt.ind.EMA(self.data.close, period=self.p.ema_fast_period)
        self.ema_slow = bt.ind.EMA(self.data.close, period=self.p.ema_slow_period)
        self.cr_fast_slow = bt.ind.CrossOver(self.ema_fast, self.ema_slow)
        self.rsi = bt.ind.RSI(self.data.close, period=self.p.rsi_period)
        self.cr_rsi_ov = bt.ind.CrossOver(self.rsi, 35.0)
        self.atr = bt.ind.ATR(self.data, period=14)
        self._peak_price = None

    def buy_or_short_condition(self):
        # BASE mean-reversion — EDGE: the bar RSI DIPS through 35, or close
        # crosses under the lower band. `rsi < 35` is a state that holds
        # for many bars and would re-enter the whole oversold stretch.
        rsi_dip = self.cr_rsi_ov[0] < 0
        base_signal = rsi_dip
        not_deep_downtrend = self.dataclose[0] > self.ema_slow[0] * 0.95
        base_signal = base_signal and not_deep_downtrend

        if base_signal:
            self.create_order(action='BUY')
            return True
        return False

    def sell_or_cover_condition(self):
        # BASE reversion exit — EDGE: back THROUGH the midline,
        # not the state of already being above it.
        rsi_recover = self.cr_rsi_ov[0] > 0
        base_exit = rsi_recover

        if not self.active_orders:
            return False
        if base_exit:
            for tracker in list(self.active_orders):
                self.close_order(tracker)
            return True
        return False
