"""
Persistent Homology Microstructure Topology with Wasserstein Mean Reversion and Ergodic Entropic Allocation
Schema: v9_concept_driven (autonomous_agency safety net)
Source hypothesis: probe
Strategy type (inferred): mean_reversion
Indicators (inferred): rsi, atr, ema
Concept keywords: persistent, homology, microstructure, topology, with, wasserstein, mean, reversion, and, ergodic, entropic, allocation
Logic keywords (contribute code): homology, microstructure, wasserstein, reversion
Logic notes: Persistent homology: 10-bar range > 3×ATR; Microstructure: bar range > 2% of open; Wasserstein-2 proxy: |close-SMA20| > 1.5×ATR; Mean-reversion: RSI<30 buy, >55 exit

Auto-generated by StrategyFactory._generate_concept_driven_code —
decomposes the hypothesis name into concept-driven logic blocks
(kalman, hawkes, wavelet, wasserstein, golden, etc.) and composes
a real BaseStrategy-pattern file. Header describes what the code does.
"""

import backtrader as bt

try:
    from .base import BaseStrategy
except ImportError:
    from autonomous_agency.strategies.base import BaseStrategy


class Persistent_Homology_Microstructure_Topology_with_Wasserstein_Mean_Reversion_and_Ergodic_Entropic_Allocation(BaseStrategy):
    """Persistent Homology Microstructure Topology with Wasserstein Mean Reversion and Ergodic Entropic Allocation (mean_reversion variant, concepts: homology, microstructure, wasserstein, reversion)"""

    params = (
        ("ema_period", 21),
        ("ema_fast_period", 12),
        ("ema_slow_period", 26),
        ("rsi_period", 14),
        ("min_votes", 1),
        # Inherited from BaseStrategy:
        # ('percent_sizer', 0.95), ('stop_loss', 2.0), ('stop_trail', 1.5),
        # ('take_profit', 4.0), ('enable_dca', True), ('dca_max_legs', 3),
        # ('dca_threshold_pct', 2.0), ('debug', False),
    )

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.rsi = bt.ind.RSI(self.data.close, period=self.p.rsi_period)
        self.ema = bt.ind.EMA(self.data.close, period=self.p.ema_period)
        self.ema_fast = bt.ind.EMA(self.data.close, period=self.p.ema_fast_period)
        self.ema_slow = bt.ind.EMA(self.data.close, period=self.p.ema_slow_period)
        self._hom_range = bt.ind.Highest(self.data.close, period=10) - bt.ind.Lowest(self.data.close, period=10)
        # Wasserstein-2 distance proxy: cumulative absolute deviation from SMA
        self._w2_sma = bt.ind.SMA(self.data.close, period=20)
        self._peak_price = None

    def buy_or_short_condition(self):
        # BASE mean-reversion — oversold OR bb-lower touch
        rsi_oversold = self.rsi[0] < 35
        bb_lower_touch = False
        not_deep_downtrend = self.dataclose[0] > self.ema_slow[0] * 0.95
        base_signal = (rsi_oversold or bb_lower_touch) and not_deep_downtrend
        # concept: homology
        gate_homology_0 = bool(self._hom_range[0] > self.atr[0] * 3)
        # concept: microstructure
        gate_microstructure_1 = bool((self.data.high[0] - self.data.low[0]) / max(self.data.open[0], 1e-9) > 0.02)
        # concept: wasserstein
        gate_wasserstein_2 = bool(abs(self.dataclose[0] - self._w2_sma[0]) > self.atr[0] * 1.5)
        # concept: reversion
        gate_reversion_3 = bool(self.rsi[0] < 30)
        # quorum, not conjunction: see module docstring
        _votes = (1 if gate_homology_0 else 0) + (1 if gate_microstructure_1 else 0) + (1 if gate_wasserstein_2 else 0) + (1 if gate_reversion_3 else 0)

        if base_signal and _votes >= max(1, self.p.min_votes):
            self.create_order(action='BUY')
            return True
        return False

    def dca_or_short_condition(self):
        if not self.in_position:
            return False
        if len(self.entry_prices) >= self.p.dca_max_legs:
            return False
        if not self.entry_prices:
            return False
        last_entry = self.entry_prices[-1]
        if self.dataclose[0] >= last_entry * (1.0 - self.p.dca_threshold_pct / 100.0):
            return False
        self.create_order(action='BUY')
        return True

    def sell_or_cover_condition(self):
        # BASE reversion exit — back to mid
        rsi_mid = self.rsi[0] > 50
        bb_mid_cross = True
        base_exit = rsi_mid or bb_mid_cross
        # concept: homology
        modifier_homology_0 = (self._hom_range[0] < self.atr[0] * 1)
        # concept: wasserstein
        modifier_wasserstein_1 = (abs(self.dataclose[0] - self._w2_sma[0]) < self.atr[0] * 0.3)
        # concept: reversion
        modifier_reversion_2 = (self.rsi[0] > 55)

        if not self.in_position:
            return False
        if base_exit or modifier_homology_0 or modifier_wasserstein_1 or modifier_reversion_2:
            self.close_all()
            return True
        return False
