"""
Generated Strategy: Active_Inference_Free_Energy_Momentum_with_Hysteretic_Precision_Gating_and_Natural_Gradient_Wasserstein_Kelly_AIFEM_HPG_NGWK_20260623_085319

Auto-generated from hypothesis: hyp_20260623_085212_0
Description: A momentum strategy grounded in the Free Energy Principle of active inference. A hierarchical generative model over latent drift and stochastic volatility produces variational free energy as a unified signal. Precision-weighted prediction error drives momentum, hysteresis prevents regime whipsaws, and position sizing uses a Wasserstein-regularized natural-gradient Kelly that respects information-geometric curvature of the statistical manifold of returns.

Generated at: 2026-06-23T08:53:19.726286
Rationale: The Free Energy Principle provides a single, mathematically rigorous objective (bound on log marginal likelihood) that simultaneously measures model fit and complexity. Hierarchical Gaussian state-space model captures both drift and stochastic volatility, with precision as a natural regime indicator. Hysteretic precision gating implements a two-bound filter that prevents rapid regime flips during genuine uncertainty. The Fisher information matrix endows return space with a Riemannian metric; the natural gradient respects this geometry, yielding updates invariant to parameterization (unlike naive gradient descent). Wasserstein-regularized Kelly is robust to model misspecification because it constrains the allocation to remain within a transport-constrained neighborhood of a conservative reference, preventing the well-documented catastrophic tail behavior of unregularized Kelly under non-Gaussian returns. This composition addresses three failure modes of standard momentum: (i) whipsaw in transitions (hysteresis), (ii) non-elliptical return geometry (Fisher metric), (iii) Kelly blow-up under fat tails (Wasserstein penalty).
"""

"""
Active_Inference_Free_Energy_Momentum_with_Hysteretic_Precision_Gating_and_Natural_Gradient_Wasserstein_Kelly_AIFEM_HPG_NGWK_20260623_085212
Schema: v9_concept_driven (autonomous_agency safety net)
Source hypothesis: hyp_20260623_085212_0
Strategy type (inferred): momentum
Indicators (inferred): ema, atr, rsi
Concept keywords: active, inference, free, energy, momentum, with, hysteretic, precision, gating, and, natural, gradient, wasserstein, kelly, aifem, hpg, ngwk
Logic keywords (contribute code): gating, wasserstein, kelly
Logic notes: Gating: stricter confirmation count required; Wasserstein-2 proxy: |close-SMA20| > 1.5×ATR; Kelly-fraction sizing: RSI>55 edge required

Auto-generated by StrategyFactory._generate_concept_driven_code —
decomposes the hypothesis name into concept-driven logic blocks
(kalman, hawkes, wavelet, wasserstein, golden, etc.) and composes
a real BaseStrategy-pattern file. Header describes what the code does.
"""

import backtrader as bt

try:
    from .base import BaseStrategy
except ImportError:
    from autonomous_agency.strategies.base import BaseStrategy


class Active_Inference_Free_Energy_Momentum_with_Hysteretic_Precision_Gating_and_Natural_Gradient_Wasserstein_Kelly_AIFEM_HPG_NGWK_20260623_085319(BaseStrategy):
    """Active_Inference_Free_Energy_Momentum_with_Hysteretic_Precision_Gating_and_Natural_Gradient_Wasserstein_Kelly_AIFEM_HPG_NGWK_20260623_085212 (momentum variant, concepts: gating, wasserstein, kelly)"""

    params = (
        ("ema_period", 21),
        ("ema_fast_period", 12),
        ("ema_slow_period", 26),
        ("rsi_period", 14),
        ("kelly_fraction", 0.5),
        # Inherited from BaseStrategy:
        # ('percent_sizer', 0.95), ('stop_loss', 2.0), ('stop_trail', 1.5),
        # ('take_profit', 4.0), ('enable_dca', True), ('dca_max_legs', 3),
        # ('dca_threshold_pct', 2.0), ('debug', False),
    )

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        with open("/home/alca/projects/PubBTQuant/.daedalus/param_probe_result.txt", "a") as _pf:
            try:
                _pf.write("self.p.stop_loss = %r\n" % (self.p.stop_loss,))
            except Exception as e:
                _pf.write("self.p.stop_loss ERR %s\n" % e)
            try:
                _pf.write("self.stop_loss  = %r\n" % (self.stop_loss,))
            except Exception as e:
                _pf.write("self.stop_loss  ERR %s\n" % e)

        self.ema = bt.ind.EMA(self.data.close, period=self.p.ema_period)
        self.ema_fast = bt.ind.EMA(self.data.close, period=self.p.ema_fast_period)
        self.ema_slow = bt.ind.EMA(self.data.close, period=self.p.ema_slow_period)
        self.rsi = bt.ind.RSI(self.data.close, period=self.p.rsi_period)
        # Wasserstein-2 distance proxy: cumulative absolute deviation from SMA
        self._w2_sma = bt.ind.SMA(self.data.close, period=20)
        self._peak_price = None

    def buy_or_short_condition(self):
        # BASE momentum — directional bias + confirmation
        # At least 1 of these signals must be true
        ema_bull = self.ema_fast[0] > self.ema_slow[0]
        macd_bull = False
        adx_strong = False
        rsi_pullback = 30 < self.rsi[0] < 75
        base_signal = sum([ema_bull, rsi_pullback]) >= 1
        # concept: wasserstein
        gate_wasserstein_0 = (abs(self.dataclose[0] - self._w2_sma[0]) > self.atr[0] * 1.5)
        # concept: kelly
        gate_kelly_1 = (self.rsi[0] > 55)

        if base_signal and gate_wasserstein_0 and gate_kelly_1:
            self.create_order(action='BUY')
            return True
        return False

    def dca_or_short_condition(self):
        if not self.in_position:
            return False
        if len(self.entry_prices) >= self.p.dca_max_legs:
            return False
        if not self.entry_prices:
            return False
        last_entry = self.entry_prices[-1]
        if self.dataclose[0] >= last_entry * (1.0 - self.p.dca_threshold_pct / 100.0):
            return False
        self.create_order(action='BUY')
        return True

    def sell_or_cover_condition(self):
        # BASE momentum exit — ema-bear OR macd-bear OR RSI-overbought
        ema_cross_dn = self.ema_fast[0] < self.ema_slow[0]
        macd_bear = False
        rsi_overbought = self.rsi[0] > 70
        base_exit = ema_cross_dn or macd_bear or rsi_overbought
        # concept: wasserstein
        modifier_wasserstein_0 = (abs(self.dataclose[0] - self._w2_sma[0]) < self.atr[0] * 0.3)

        if not self.in_position:
            return False
        if base_exit or modifier_wasserstein_0:
            self.close_all()
            return True
        return False
